CREATE SEQUENCE TB_USERS_ID_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;


CREATE TABLE TB_USERS (
    ID            NUMBER(19) DEFAULT TB_USERS_ID_SEQ.NEXTVAL PRIMARY KEY,
    NAME          VARCHAR2(150) NOT NULL,
    EMAIL         VARCHAR2(150) NOT NULL UNIQUE,
    PASSWORD      VARCHAR2(255) NOT NULL,
    BIRTH_DATE    DATE NOT NULL,
    IS_ACTIVE     NUMBER(1)   DEFAULT 1 NOT NULL,
    CREATED_AT    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP WITH TIME ZONE
);
