CREATE SEQUENCE TB_ENERGY_READINGS_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- TABLE: TB_ENERGY_READINGS
CREATE TABLE TB_ENERGY_READINGS (
    ID              NUMBER(19)   DEFAULT TB_ENERGY_READINGS_ID_SEQ.NEXTVAL PRIMARY KEY,
    SENSOR_ID       NUMBER(19)   NOT NULL,
    POWER_KW        NUMBER(10,3) NOT NULL,
    OCCUPANCY_PCT   NUMBER(5,2)  NOT NULL,
    TAKEN_AT        TIMESTAMP    DEFAULT SYSTIMESTAMP                 NOT NULL,
    CONSTRAINT FK_READINGS_SENSOR
        FOREIGN KEY (SENSOR_ID)
        REFERENCES TB_SENSORS (ID)
);

CREATE INDEX IDX_READINGS_SENSOR   ON TB_ENERGY_READINGS (SENSOR_ID);
CREATE INDEX IDX_READINGS_TAKEN_AT ON TB_ENERGY_READINGS (TAKEN_AT);
