CREATE SEQUENCE TB_CONSUMPTION_LIMITS_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- TABLE: TB_CONSUMPTION_LIMITS
CREATE TABLE TB_CONSUMPTION_LIMITS (
    ID              NUMBER(19)   DEFAULT TB_CONSUMPTION_LIMITS_ID_SEQ.NEXTVAL PRIMARY KEY,
    EQUIPMENT_ID    NUMBER(19)   NOT NULL,
    LIMIT_KWH       NUMBER(10,3) NOT NULL,
    COMPUTED_AT     DATE         NOT NULL,
    CONSTRAINT UQ_LIMIT_EQUIP_DAY UNIQUE (EQUIPMENT_ID, COMPUTED_AT),
    CONSTRAINT FK_LIMIT_EQUIPMENT
        FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES TB_EQUIPMENTS (ID)
);

CREATE INDEX IDX_LIMIT_EQUIPMENT ON TB_CONSUMPTION_LIMITS (EQUIPMENT_ID);
