CREATE SEQUENCE TB_AUTOMATIC_ACTIONS_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- TABLE: TB_AUTOMATIC_ACTIONS
CREATE TABLE TB_AUTOMATIC_ACTIONS (
    ID              NUMBER(19)   DEFAULT TB_AUTOMATIC_ACTIONS_ID_SEQ.NEXTVAL PRIMARY KEY,
    EQUIPMENT_ID    NUMBER(19)   NOT NULL,
    TYPE            VARCHAR2(40)  NOT NULL,
    DETAILS         VARCHAR2(500) NOT NULL,
    EXECUTED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ACTION_EQUIPMENT
        FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES TB_EQUIPMENTS (ID)
);

CREATE INDEX IDX_ACTION_EQUIPMENT ON TB_AUTOMATIC_ACTIONS (EQUIPMENT_ID);
