CREATE SEQUENCE TB_DAILY_REPORTS_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TB_DAILY_REPORTS (
    ID                NUMBER(19) DEFAULT TB_DAILY_REPORTS_ID_SEQ.NEXTVAL PRIMARY KEY,
    EQUIPMENT_ID      NUMBER(19) NOT NULL,
    REPORT_DATE       DATE NOT NULL,
    CONSUMPTION_KWH   NUMBER(19,4) NOT NULL,
    CO2_EMISSION_KG   NUMBER(19,4) NOT NULL,
    EFFICIENCY_RATING VARCHAR2(20) NOT NULL,
    CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DAILY_REPORT_EQUIP
        FOREIGN KEY (EQUIPMENT_ID) REFERENCES TB_EQUIPMENTS(ID)
);
