CREATE SEQUENCE TB_ALERTS_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
  NOCYCLE;

CREATE TABLE TB_ALERTS (
    ID                NUMBER(19) DEFAULT TB_ALERTS_ID_SEQ.NEXTVAL PRIMARY KEY,
    EQUIPMENT_ID      NUMBER(19) NOT NULL,
    ALERT_DATE        DATE NOT NULL,
    CONSUMPTION_KWH   NUMBER(19,4) NOT NULL,
    LIMIT_KWH         NUMBER(19,4) NOT NULL,
    EXCEEDED_BY_KWH   NUMBER(19,4) NOT NULL,
    MESSAGE           VARCHAR2(500),
    CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ALERTS_EQUIP
        FOREIGN KEY (EQUIPMENT_ID)
        REFERENCES TB_EQUIPMENTS(ID)
);
