name: CI/CD Pipeline - Voltly

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Job de Testes e Build
  test-and-build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: voltly_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'eclipse-temurin'

    - name: Cache dependências Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Executar testes unitários
      run: ./mvnw test
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/voltly_test
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_PROFILES_ACTIVE: test

    - name: Executar testes de integração
      run: ./mvnw verify -P integration-tests
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/voltly_test
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        SPRING_PROFILES_ACTIVE: test

    - name: Gerar relatório de cobertura
      run: ./mvnw jacoco:report

    - name: Upload relatório de cobertura
      uses: codecov/codecov-action@v3
      with:
        file: ./target/site/jacoco/jacoco.xml

    - name: Build da aplicação
      run: ./mvnw clean package -DskipTests

    - name: Upload artefatos
      uses: actions/upload-artifact@v3
      with:
        name: jar-artifact
        path: target/*.jar

  # Job de Build e Push da Imagem Docker
  build-and-push:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login no GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extrair metadados
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build e push da imagem Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Job de Deploy para Staging
  deploy-staging:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: staging

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Deploy para Staging
      run: |
        echo "Deploying to staging environment..."
        # Aqui você pode adicionar comandos específicos para deploy no staging
        # Por exemplo: kubectl apply, docker-compose up, etc.
        echo "Staging deployment completed!"

  # Job de Deploy para Produção
  deploy-production:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Deploy para Produção
      run: |
        echo "Deploying to production environment..."
        # Aqui você pode adicionar comandos específicos para deploy em produção
        # Por exemplo: kubectl apply, docker-compose up, etc.
        echo "Production deployment completed!"

  # Job de Notificação
  notify:
    needs: [test-and-build, build-and-push]
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Notificar sucesso
      if: needs.test-and-build.result == 'success' && needs.build-and-push.result == 'success'
      run: |
        echo "✅ Pipeline executado com sucesso!"
        echo "🚀 Aplicação deployada com sucesso!"

    - name: Notificar falha
      if: needs.test-and-build.result == 'failure' || needs.build-and-push.result == 'failure'
      run: |
        echo "❌ Pipeline falhou!"
        echo "🔍 Verifique os logs para mais detalhes."
